export const MAP_FETCH = 'MAP_FETCH'
export const MAP_SEED = 'MAP_SEED'
export const MAP_DELETE_POINT = 'MAP_DELETE_POINT'
export const MAP_FETCH_MAIN_GRID = 'MAP_FETCH_MAIN_GRID'

export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE'
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
